### PR TITLE
Support for Linux Boards 

### PR DESCRIPTION
**Pull request by olixr**
- Blinka migration

### CODE REVIEW

**Comment by SecT0uch** [comment]
This PR does not include our last commits

**Comment by olixr** [comment]
Are they not in the branch? I just pulled from your repo on the blinka branch. 

We can cancel and new PR?

**Comment by SecT0uch** [comment]
Never mind, I was reading the commit list in the wrong direction x)

**Comment by olixr** [comment]
I have resolved conflicts and merged work into my `feature` branch at this time to continue local testing.

**Pull request merged**
