### PR TITLE
Fix issue on logging

### PR DESCRIPTION
**Pull request by yeyeto2788**
Initially was a dirty fix for the logging issue. Please refer to PR #18

Now I added more lint fixes and also get rid of the check with regex for pin validation and leave it for `blinka` to validate pin being used.

### CODE REVIEW

**Comment by yeyeto2788** [comment]
I pulled your changes into my fork so you don't have too much problems to merge my changes.

I noticed I did not get any readings from the DHT sensor 🤒 

```console

███╗   ███╗██╗   ██╗██████╗ ██████╗ ██╗
████╗ ████║██║   ██║██╔══██╗██╔══██╗██║
██╔████╔██║██║   ██║██║  ██║██████╔╝██║
██║╚██╔╝██║██║   ██║██║  ██║██╔═══╝ ██║
██║ ╚═╝ ██║╚██████╔╝██████╔╝██║     ██║
╚═╝     ╚═╝ ╚═════╝ ╚═════╝ ╚═╝     ╚═╝
____________________________________________________________

Eric Davisson @MudPiApp
https://mudpi.app
Version:  0.10.0

Loading MudPi Configs ............................... Complete
DEBUG MODE ENABLED
Config path: /home/yeyeto2788/workspace/mudpi-core/mudpi.json
Current Directory: /home/yeyeto2788/workspace/mudpi-core
Initializing Logger  ................................ Complete
Preparing State Manager  ............................ Complete
Preparing Event System for redis  ................... Pending
Event System Ready on redis   ....................... Connected
Initializing Core  .................................. Complete
_________________ Detecting Configurations _________________
Detecting Configurations ............................ Pending
Detected 1 Non-Core Configurations .................. Complete
Preparing 1 Configurations to be Loaded  ............ Pending
Sensor Ready for Import ............................. Ready
1 Configurations Ready to Load  ..................... Complete
_____________________ Load Extensions ______________________
Loading 1 Configurations into Extensions  ........... Pending
Loading: sensor
Importing Sensor .................................... Pending
Imported Sensor ..................................... Success
Dht Ready for Import ................................ Ready
Dht requirements .................................... Installing
Installing package adafruit-circuitpython-dht==3.5.5
Importing dht:sensor ................................ Pending
Imported dht:sensor ................................. Success
Configuration for dht:sensor ........................ Validated
Example Ready for Import ............................ Ready
Importing example:sensor ............................ Pending
Imported example:sensor ............................. Success
Configuration for example:sensor .................... Validated
Sensor Configuration ................................ Validated
Initializing Sensor ................................. Pending
Importing Dht ....................................... Pending
Imported Dht ........................................ Success
Dht Configuration ................................... Validated
Extension dht did not define an `init()` method.
Initializing Dht .................................... Pending
Initialized Dht ..................................... Success
can't set attribute
Loaded 1 Extensions  ................................ Complete
MudPi Fully Loaded .................................. Complete
______________________ Start Systems _______________________
Starting All Workers  ............................... Pending
Started All Workers  ................................ Complete
MudPi Systems   ..................................... Online
____________________________________________________________

MUDPI LOADED EXTENSIONS
Namespace: dht
Provides interface for DHT sensors to take climate readings.
https://mudpi.app/docs/pi-sensors-humidity
MUDPI DISABLED EXTENSIONS
MUDPI REGISTERED ACTIONS
ACTION CALL                                        ACTION
--------------------------------------------------------------------------------
mudpi.turn_on                                    | turn_on
mudpi.turn_off                                   | turn_off
mudpi.shutdown                                   | shutdown
____________________________________________________________
^C____________________________________________________________
Stopping All Workers for Shutdown   ................. Pending
All MudPi Systems   ................................. Offline
```

**Comment by yeyeto2788** [comment]
Hey @olixr,

Want me to keep updating this PR? Shouldn't we merge it?

**Comment by olixr** [comment]
Yes I plan to merge this in, I got busy with fixes and testing. So most of the items are working well but like you I also had issues with the DHT on some of my boards. 

I read this tonight: https://github.com/adafruit/Adafruit_CircuitPython_DHT/issues/33 and it looks like many others are having issues with this on older boards. Not sure what changed in the library but might need to consider older version for better response on some boards. 

Also I ran into some ARMv6 vs ARMv7 support finally. After about 10+ corrupted kernels and flashes on the Pi zero I figured out some libraries were not working. We may need to utilize this check to also do something about the DHT. 

For now perhaps increasing the `read_attempts` config to a larger number may force it to read with the cost of more time.

**Comment by yeyeto2788** [comment]
Hey @olixr I had some similar issues with the sensor and that's why I reported it [here](https://github.com/adafruit/Adafruit_CircuitPython_DHT/issues/66) and I also made a PR with [this](https://github.com/adafruit/Adafruit_CircuitPython_DHT/pull/68) script which let's you change the default timing for the sensor and get better readings. 

I would suggest to increase the read attempt but no more than 5 since that would be depending on the sensor up to 10 secs if we wait 2 seconds per read which in my opinion is not that cool to wait. I would also suggest (even add a note on the docs) to rely on a different sensor using another protocol like I2C/SPI or even use the same sensor with nanpy 😄

**Review by olixr — APPROVED** [review]

**Pull request merged**
